/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.brilltech.maaser.entities.Campaign', null, global);
goog.exportSymbol('proto.brilltech.maaser.entities.Campaign.ReceiverType', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.brilltech.maaser.entities.Campaign = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.brilltech.maaser.entities.Campaign, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.brilltech.maaser.entities.Campaign.displayName = 'proto.brilltech.maaser.entities.Campaign';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.brilltech.maaser.entities.Campaign.prototype.toObject = function(opt_includeInstance) {
  return proto.brilltech.maaser.entities.Campaign.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.brilltech.maaser.entities.Campaign} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.Campaign.toObject = function(includeInstance, msg) {
  var f, obj = {
    campaignid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    targetamount: jspb.Message.getFieldWithDefault(msg, 2, 0),
    countrycode: jspb.Message.getFieldWithDefault(msg, 3, ""),
    title: jspb.Message.getFieldWithDefault(msg, 4, ""),
    receivertype: jspb.Message.getFieldWithDefault(msg, 5, 0),
    receivername: jspb.Message.getFieldWithDefault(msg, 6, ""),
    category: jspb.Message.getFieldWithDefault(msg, 7, ""),
    description: jspb.Message.getFieldWithDefault(msg, 8, ""),
    collectedamount: jspb.Message.getFieldWithDefault(msg, 9, 0),
    thumbnailurl: jspb.Message.getFieldWithDefault(msg, 10, ""),
    accountid: jspb.Message.getFieldWithDefault(msg, 11, ""),
    createdat: jspb.Message.getFieldWithDefault(msg, 12, 0),
    updatedat: jspb.Message.getFieldWithDefault(msg, 13, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.brilltech.maaser.entities.Campaign}
 */
proto.brilltech.maaser.entities.Campaign.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.brilltech.maaser.entities.Campaign;
  return proto.brilltech.maaser.entities.Campaign.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.brilltech.maaser.entities.Campaign} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.brilltech.maaser.entities.Campaign}
 */
proto.brilltech.maaser.entities.Campaign.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCampaignid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTargetamount(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCountrycode(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 5:
      var value = /** @type {!proto.brilltech.maaser.entities.Campaign.ReceiverType} */ (reader.readEnum());
      msg.setReceivertype(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setReceivername(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setCategory(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCollectedamount(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setThumbnailurl(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccountid(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatedat(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUpdatedat(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.brilltech.maaser.entities.Campaign.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.brilltech.maaser.entities.Campaign.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.brilltech.maaser.entities.Campaign} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.Campaign.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCampaignid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTargetamount();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getCountrycode();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getReceivertype();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getReceivername();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getCategory();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getCollectedamount();
  if (f !== 0) {
    writer.writeInt64(
      9,
      f
    );
  }
  f = message.getThumbnailurl();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getAccountid();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getCreatedat();
  if (f !== 0) {
    writer.writeInt64(
      12,
      f
    );
  }
  f = message.getUpdatedat();
  if (f !== 0) {
    writer.writeInt64(
      13,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.brilltech.maaser.entities.Campaign.ReceiverType = {
  UNKNOWN_RECEIVER: 0,
  MYSELF: 1,
  OTHERS: 2
};

/**
 * optional string campaignId = 1;
 * @return {string}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getCampaignid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.brilltech.maaser.entities.Campaign.prototype.setCampaignid = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 targetAmount = 2;
 * @return {number}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getTargetamount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.brilltech.maaser.entities.Campaign.prototype.setTargetamount = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string countryCode = 3;
 * @return {string}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getCountrycode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.brilltech.maaser.entities.Campaign.prototype.setCountrycode = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string title = 4;
 * @return {string}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.brilltech.maaser.entities.Campaign.prototype.setTitle = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional ReceiverType receiverType = 5;
 * @return {!proto.brilltech.maaser.entities.Campaign.ReceiverType}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getReceivertype = function() {
  return /** @type {!proto.brilltech.maaser.entities.Campaign.ReceiverType} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {!proto.brilltech.maaser.entities.Campaign.ReceiverType} value */
proto.brilltech.maaser.entities.Campaign.prototype.setReceivertype = function(value) {
  jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional string receiverName = 6;
 * @return {string}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getReceivername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.brilltech.maaser.entities.Campaign.prototype.setReceivername = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string category = 7;
 * @return {string}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getCategory = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.brilltech.maaser.entities.Campaign.prototype.setCategory = function(value) {
  jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string description = 8;
 * @return {string}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.brilltech.maaser.entities.Campaign.prototype.setDescription = function(value) {
  jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional int64 collectedAmount = 9;
 * @return {number}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getCollectedamount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.brilltech.maaser.entities.Campaign.prototype.setCollectedamount = function(value) {
  jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional string thumbnailUrl = 10;
 * @return {string}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getThumbnailurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/** @param {string} value */
proto.brilltech.maaser.entities.Campaign.prototype.setThumbnailurl = function(value) {
  jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string accountId = 11;
 * @return {string}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getAccountid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/** @param {string} value */
proto.brilltech.maaser.entities.Campaign.prototype.setAccountid = function(value) {
  jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional int64 createdAt = 12;
 * @return {number}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getCreatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/** @param {number} value */
proto.brilltech.maaser.entities.Campaign.prototype.setCreatedat = function(value) {
  jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional int64 updatedAt = 13;
 * @return {number}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getUpdatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/** @param {number} value */
proto.brilltech.maaser.entities.Campaign.prototype.setUpdatedat = function(value) {
  jspb.Message.setProto3IntField(this, 13, value);
};


goog.object.extend(exports, proto.brilltech.maaser.entities);
